### ISSUE TITLE
There isn't any good project is from China. 

### ISSUE THREAD

**Issue by lixingyangok** [slowernews/awesome-open-source-by-country-or-region#2]

**Comment by DavidWhom** [comment]
这老外歧视咱

**Comment by nieweiming** [comment]
连个中国的都没有，你收集个锤子！

**Comment by nieweiming** [comment]
thsi project is shit!

**Comment by neederhow** [comment]
它把台湾算一个国家，屁股下是什么屎还不明白吗

**Comment by DavidWhom** [comment]
这东西还是阮一峰老是引过来的

**Comment by Guevara666** [comment]
这玩意儿还是阮一峰老师引过来的

**Comment by slowernews** [comment]
A list with Chinese projects, AFAIK, doesn't exist yet!

I think the best template is the [Russia](https://github.com/igoradamenko/awesome-made-by-russians) repository. So feel free to start one and I'll add it here.

Edit: [Found one from China already.](https://github.com/JN-H/awesome-made-by-chinese)

**Comment by DavidWhom** [comment]
Taiwan is not a country! Please modify it. Change the title 'country' to 'area'

**Comment by slowernews** [comment]
"Readme" and "About" updated.

Anyway this list is not - and never was - political. It should be seen like a friendly sports competition. Nothing else.
